apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-pi
  namespace: default
spec:
  type: Python
  mode: cluster
  image: datamechanics/spark:2.4.5-hadoop-3.1.0-java-8-scala-2.11-python-3.7-dm14
  mainApplicationFile: "/opt/spark/examples/src/main/python/pi.py"
  arguments:
  - '1000'
  sparkVersion: "2.4.5"
  executor:
    cores: 1
    instances: 1
    memory: "512m"
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
  restartPolicy:
    type: Never
